version: '3.1'

services:
  image-store-service:
    image: "paulobaena/image-store-service:latest"
    hostname: "image-store-service"
    container_name: "image-store-service"
    env_file:
      - local.env
    ports:
      - "8080:8080"
