version: '3.1'

services:
  image-store-service:
    image: "paulobaena/image-store-service:latest"
    hostname: image-store-service
    container_name: image-store-service
    env_file:
      - local.env
    ports:
      - "8080:8080"
    depends_on:
      - elasticsearch
  elasticsearch:
    restart: on-failure
    image: "elasticsearch:6.4.0"
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"